### ISSUE TITLE
What `if/unless_defined?` macros are for?

### ISSUE THREAD

**Issue by Sija** [wyhaines/defined.cr#4]
Hi,

I'm just wondering what above-mentioned macros are for, considering we can just write `if defined?` or `unless defined?`.

There might be some magic sauce included, though I couldn't find any mention of it within the README and I'm too lazy atm to check the source code for the answer ;)

**Comment by wyhaines** [comment]
Compile-time evaluation.

It's just that `if defined?` evaulates the if expression at runtime, whereas the `if_defined?` macro evaluates the if expression at compile time.

The original reason for this, way back when I first wrote it, was to do conditional insertion of other code, depending on whether or not a constant was set. You can't do that at compile time.

These days, almost all of my usage is with the other, more specialized macros defined in the package.

**Comment by Sija** [comment]
If `defined?` is a macro, the whole `if/unless` branch will be most likely optimized by LLVM anyway, isn't this so?

**Comment by wyhaines** [comment]
There are some things that can't evaluate dynamically, like `require`:

```
In a.cr:2:3

 2 | require "./b"
     ^
Error: can't require dynamically
```

So, if one wants to see if something is defined, and if it isn't, load a shim library, or some sort of stopgap library to provide that thing, one has to do the whole thing within a macro. This was the original impetus for `if_defined?`/`unless_defined?`.

**Comment by Sija** [comment]
Totally forgot about the requires! Thanks for bearing with me and the explanation :)
I guess that's sth that might be good to find in README, btw.
